### ISSUE TITLE
Server stopped

### ISSUE THREAD

**Issue by leorke** [captainwasabi/topologrjs#36]
Hello, I have installed the "topologrjs" app in a Rpi3B+ with Buster. I start the server through an SSH connection (Putty) with the command line: "node app.js"  and all is working nicely. When I close Putty the server halts. What am I missing ?

**Comment by captainwasabi** [comment]
Use this:

```PORT=3000 nohup node app.js 2>&1 >> topologr.log &```

**Comment by captainwasabi** [comment]
so you should be able to put that command in rc.local and it will start at reboot.  Or put it in your crontab with the @reboot syntax (i.e. `@reboot PORT=3000 nohup node app.js 2>&1 >> topologr.log &`  but I think my preferred way is going to be to use pm2 (https://pm2.keymetrics.io/) which I will document in the README with the next code release.  (which is taking longer than I would like because I have not had much time to focus on it.)

**Comment by leorke** [comment]
Thanks again for your prompt support.
73 de I3RKE/AC2OG

**Comment by captainwasabi** [comment]
See #30
